### ISSUE TITLE
Evaluate scripts.

### ISSUE THREAD

**Issue by Colmar-zlicheng** [OpenRobotLab/UniHSI#10]
Hi, can you please provide test/evaluate scripts (such as how to compute success rate and dump results)? I try to use the command below, but I met segmentation fault when I set `--obj_file` as `sceneplan/partnet_test_simple.json`.

```
python3 unihsi/run.py \
    --task UniHSI_PartNet\
    --test \
    --num_envs 1 \
    --cfg_env unihsi/data/cfg/humanoid_unified_interaction_scene_64.yaml \
    --cfg_train unihsi/data/cfg/train/rlg/amp_humanoid_task_deep_layer_2we.yaml \
    --motion_file motion_clips/chair_mo.npy \
    --checkpoint output/Humanoid_31-17-04-30/nn/Humanoid.pth \
    --obj_file sceneplan/partnet_train_simple.json
```

**Comment by xizaoqu** [comment]
Hi, you can evaluate it by recording the states (whether fulfilled, distance) when resetting the task and summarizing them on specified samples. I'm not sure how the segmentation fault happens.

**Comment by xizaoqu** [comment]
Hi, I've updated the evaluation scripts. Please have a try.
