### ISSUE TITLE
How to test with different environment and prompt

### ISSUE THREAD

**Issue by bowieshi** [OpenRobotLab/UniHSI#11]
Hi. Can I ask how can we use different Scene or use PartNet object and try different action? In paper, it is "chain_of_contacts". But in the scannet_example.json, it is "contact_pairs". What is the difference? If I want to test the examples provided in the paper. How can I modify the bash file? Thank you!
```
python3 unihsi/run.py \
    --task UniHSI_ScanNet\
    --test \
    --num_envs 1 \
    --cfg_env unihsi/data/cfg/humanoid_unified_interaction_scene_1.yaml \
    --cfg_train unihsi/data/cfg/train/rlg/amp_humanoid_task_deep_layer.yaml \
    --motion_file motion_clips/chair_mo014.npy \
    --checkpoint checkpoints/Humanoid.pth \
    --obj_file sceneplan_demo/scannet_example.json
```

**Comment by xizaoqu** [comment]
Hi. "chain_of_contacts" in the paper and "contact_pairs" in the config are the same thing. If you want to test other examples, just write another config in the form of scannet_example.json.

**Comment by xizaoqu** [comment]
Hi, I'll close the comment. Feel free to reopen it if you have further questions.
