### ISSUE TITLE
obj_list

### ISSUE THREAD

**Issue by zitengji0618** [OpenRobotLab/UniHSI#13]
First of all, I want to thank you for presenting this wonderful achievement.

I am having this problem where the obj_list contains strings of numbers like "3037" for PartNet data, but the data in stats folder of PartNet has actual name of the object instead of numbers. Am I doing this right? How can I fix the issue?

Thank you

**Comment by appprovider** [comment]
Hi, I'm also wondering about the answer to this question. Is it necessary to extract all the obj files from each numbered folder, or should the source code be modified?
