### ISSUE TITLE
wandb & fbx 

### ISSUE THREAD

**Issue by zitengji0618** [OpenRobotLab/UniHSI#14]
Thank you for presenting this amazing work!

Are wandb and fbx necessary in this work?

Thank you

**Comment by xizaoqu** [comment]
Hi, wandb is recommended to view and record the training process but not necessary. fbx is also not necessary if you can directly get the motion files.

**Comment by xizaoqu** [comment]
Hi, I'll close the comment. Feel free to reopen it if you have further questions.
