### ISSUE TITLE
How can I obtain PartNet data in the same format as listed?

### ISSUE THREAD

**Issue by yhr0710** [OpenRobotLab/UniHSI#16]
Why is the format of the PartNet data I obtained like the one shown in the figure below? How can I obtain data in the same format as yours?
<img width="654" alt="1c0d5bdf-8be1-4a47-be4b-3f6a8ba78c4a" src="https://github.com/user-attachments/assets/6eb45269-a770-436a-a8e1-b6b8d12898ff">

**Comment by appprovider** [comment]
I'm also wondering about the answer to this question. Is it necessary to extract all the obj files from each numbered folder, or should the source code be modified?
