### ISSUE TITLE
Code release date?

### ISSUE THREAD

**Issue by Steve-Tod** [OpenRobotLab/UniHSI#3]
Hi,

Thank you for presenting this exciting work! I was wondering when the code will be released so I can have a try.

**Comment by xizaoqu** [comment]
Hi, thank you for your attention to our work. Our work is currently in submission. The code is expected to be released after that.

**Comment by happened** [comment]
Thank you for presenting this exciting work! I was wondering when the code will be released so I can have a try.. too :)
