### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'samp_amp/chair_mo014.npy'

### ISSUE THREAD

**Issue by kwon-ohhyeok** [OpenRobotLab/UniHSI#4]
thank you for great work of your team.

./demo_scannet.sh gives me an error like:
FileNotFoundError: [Errno 2] No such file or directory: 'samp_amp/chair_mo014.npy'

where should I find this file?
thank you.

**Comment by xizaoqu** [comment]
Hi, I've updated an example motion file. You may try it again. Thanks.

**Comment by kwon-ohhyeok** [comment]
oh..! thank you for fast reply. i'll try it right now.

**Comment by kwon-ohhyeok** [comment]
![image](https://github.com/OpenRobotLab/UniHSI/assets/147812423/b08749d0-67d6-4cbc-a754-ae6959fc738f)

yeh~~!. it works. thank you!

**Comment by xizaoqu** [comment]
I just pushed an updated checkpoint, you can also try it.

**Comment by kwon-ohhyeok** [comment]
oh..! I've renamed current "Humanoid.pth" to "Humanoid2.pth". it works waaaaay better then previous one. thank you for great work. i'll notice you when i've done further research over this great work.

I hope everything what you are doing now goes well.
have a great day fellow. :)
