### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'motion_clips/lie_down_2.npy'

### ISSUE THREAD

**Issue by Colmar-zlicheng** [OpenRobotLab/UniHSI#7]
Hi, I got this error when I run the example `sh train_partnet_simple.sh`.
Could you please give the motion clip process file?

**Comment by xizaoqu** [comment]
Hi, I've uploaded the missing clips.

**Comment by Colmar-zlicheng** [comment]
Thank you!
